### ISSUE TITLE
Estas a pocos pasos de terminar!

### ISSUE THREAD

**Issue by danmt** [sebatustra/heavy-duty-camp-seba#1]
Solo una cosita, me equivoque en la presentación y me falto mencionar algo de webpack que es necesario... peeeero, por solucion temporal, reemplaza el contenido de [https://github.com/sebatustra/heavy-duty-camp-seba/blob/main/src/polyfills.ts](https://github.com/sebatustra/heavy-duty-camp-seba/blob/main/src/polyfills.ts) con esto:

```ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Buffer } from "buffer";

(window as any).global = window;
(window as any).global.Buffer = Buffer;
(window as any).process = { env: { }}; 
```

**Comment by sebatustra** [comment]
listo compa
